[2024-04-28T21:17:36.283-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T21:17:36.321-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.read_currency manual__2024-04-29T00:16:33.182555+00:00 [queued]>
[2024-04-28T21:17:36.338-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.read_currency manual__2024-04-29T00:16:33.182555+00:00 [queued]>
[2024-04-28T21:17:36.339-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T21:17:36.366-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): read_currency> on 2024-04-29 00:16:33.182555+00:00
[2024-04-28T21:17:36.376-0300] {standard_task_runner.py:63} INFO - Started process 12376 to run task
[2024-04-28T21:17:36.380-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'read_currency', 'manual__2024-04-29T00:16:33.182555+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmpxqm0g4ep']
[2024-04-28T21:17:36.381-0300] {standard_task_runner.py:91} INFO - Job 45: Subtask read_currency
[2024-04-28T21:17:36.438-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.read_currency manual__2024-04-29T00:16:33.182555+00:00 [running]> on host ath
[2024-04-28T21:17:36.567-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='read_currency' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:16:33.182555+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T00:16:33.182555+00:00'
[2024-04-28T21:17:36.569-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T21:17:36.580-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T21:17:36.581-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/dags/atividade_pratica_dag.py", line 38, in read_currency
    airflow_home + "/data/currency.csv"
    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2024-04-28T21:17:36.591-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica_dag, task_id=read_currency, execution_date=20240429T001633, start_date=20240429T001736, end_date=20240429T001736
[2024-04-28T21:17:36.893-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task read_currency (unsupported operand type(s) for +: 'NoneType' and 'str'; 12376)
[2024-04-28T21:17:36.954-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T21:17:36.987-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T21:17:36.989-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
