[2024-04-28T21:07:40.663-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T21:07:40.686-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.decide_branch manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:07:40.695-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.decide_branch manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:07:40.695-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T21:07:40.715-0300] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): decide_branch> on 2024-04-29 00:07:07.430511+00:00
[2024-04-28T21:07:40.722-0300] {standard_task_runner.py:63} INFO - Started process 11497 to run task
[2024-04-28T21:07:40.726-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'decide_branch', 'manual__2024-04-29T00:07:07.430511+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmplazs01d7']
[2024-04-28T21:07:40.727-0300] {standard_task_runner.py:91} INFO - Job 16: Subtask decide_branch
[2024-04-28T21:07:40.776-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.decide_branch manual__2024-04-29T00:07:07.430511+00:00 [running]> on host ath
[2024-04-28T21:07:40.872-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='decide_branch' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:07:07.430511+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T00:07:07.430511+00:00'
[2024-04-28T21:07:40.873-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T21:07:40.874-0300] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-28T21:07:40.875-0300] {python.py:237} INFO - Done. Returned value was: path_does_not_exist
[2024-04-28T21:07:40.875-0300] {branch.py:36} INFO - Branch into path_does_not_exist
[2024-04-28T21:07:40.875-0300] {skipmixin.py:178} INFO - Following branch path_does_not_exist
[2024-04-28T21:07:40.876-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T21:07:40.895-0300] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=atividade_pratica_dag, task_id=decide_branch, execution_date=20240429T000707, start_date=20240429T000740, end_date=20240429T000740
[2024-04-28T21:07:40.938-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T21:07:40.964-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T21:07:40.965-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
