[2024-04-28T21:08:32.927-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T21:08:32.952-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.update_currency_csv manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:08:32.964-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.update_currency_csv manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:08:32.964-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T21:08:32.981-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): update_currency_csv> on 2024-04-29 00:07:07.430511+00:00
[2024-04-28T21:08:32.988-0300] {standard_task_runner.py:63} INFO - Started process 11559 to run task
[2024-04-28T21:08:32.992-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'update_currency_csv', 'manual__2024-04-29T00:07:07.430511+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmpronn1i7e']
[2024-04-28T21:08:32.993-0300] {standard_task_runner.py:91} INFO - Job 24: Subtask update_currency_csv
[2024-04-28T21:08:33.038-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.update_currency_csv manual__2024-04-29T00:07:07.430511+00:00 [running]> on host ath
[2024-04-28T21:08:33.122-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='update_currency_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:07:07.430511+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T00:07:07.430511+00:00'
[2024-04-28T21:08:33.124-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T21:08:33.133-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T21:08:33.133-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/dags/atividade_pratica_dag.py", line 47, in update_currency_csv
    airflow_home + "/data/currency_updated.csv"
    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2024-04-28T21:08:33.142-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica_dag, task_id=update_currency_csv, execution_date=20240429T000707, start_date=20240429T000832, end_date=20240429T000833
[2024-04-28T21:08:33.329-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task update_currency_csv (unsupported operand type(s) for +: 'NoneType' and 'str'; 11559)
[2024-04-28T21:08:33.364-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T21:08:33.381-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T21:08:33.382-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
