[2024-04-28T21:08:13.568-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T21:08:13.592-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.read_currency manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:08:13.604-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.read_currency manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:08:13.605-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T21:08:13.632-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): read_currency> on 2024-04-29 00:07:07.430511+00:00
[2024-04-28T21:08:13.639-0300] {standard_task_runner.py:63} INFO - Started process 11531 to run task
[2024-04-28T21:08:13.643-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'read_currency', 'manual__2024-04-29T00:07:07.430511+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmp0_uyr2pi']
[2024-04-28T21:08:13.644-0300] {standard_task_runner.py:91} INFO - Job 21: Subtask read_currency
[2024-04-28T21:08:13.689-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.read_currency manual__2024-04-29T00:07:07.430511+00:00 [running]> on host ath
[2024-04-28T21:08:13.771-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='read_currency' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:07:07.430511+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T00:07:07.430511+00:00'
[2024-04-28T21:08:13.772-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T21:08:13.781-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T21:08:13.781-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/dags/atividade_pratica_dag.py", line 38, in read_currency
    airflow_home + "/data/currency.csv"
    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2024-04-28T21:08:13.789-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica_dag, task_id=read_currency, execution_date=20240429T000707, start_date=20240429T000813, end_date=20240429T000813
[2024-04-28T21:08:14.017-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task read_currency (unsupported operand type(s) for +: 'NoneType' and 'str'; 11531)
[2024-04-28T21:08:14.056-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T21:08:14.074-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T21:08:14.075-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
